name: SBOM
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate SBOM
    # Check commit message to not infinitely run action
    if: "!contains(github.event.head_commit.message, 'Commit SBOM')"
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - run: npm ci

      - name: Create SBOM with CycloneDX
        uses: CycloneDX/gh-node-module-generatebom@master
        with: 
          output: './sbom.xml'

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit SBOM
          file_pattern: 'sbom.xml'


